# Descriptor calculation target
geometry_msgs/Pose target
---
# Index of the point used for calculation
std_msgs/Int32 index

# Computed descriptor
std_msgs/Float64[] descriptor

# Params used to compute the descriptor 
pr2_grasping/DescriptorParams params