---
########## nodes params ##########

# flags to enable/disable debug
setupDebug: false
labelerDebug: false
analyzerDebug: false
grasperDebug: false
evaluatorDebug: false
gmonitorDebug: false


##### setup node options #####
setup:
    # true if torso/arms/base/head setup has to be performed
    liftTorso: false
    moveArms: true
    moveBase: false
    moveHead: true

    # setup positions 
    torsoPosition: 0.19
    displacementThreshold: 1.0
    headTarget: {x: 0.9, y: 0.0, z: 0.5}
    armsPosition:
      right: {x: 0.0, y: -0.7, z: 0.9}
      left: {x: 0.0, y: 0.7, z: 0.9}

    # objects ignored in the reset process
    ignore: [ground_plane, pr2]
    support: low_table


##### labeler node options #####
labeler:
    # point cloud input topic
    pointcloudTopic: /head_mount_kinect/depth_registered/points
    # sampling voxel size (value < 0 to don't downsample)
    voxelSize: -1
    # location of the codebook file
    codebookLocation: config/codebook_200-32_c7_1E-04_opencv.dat
    # clipping plane position in Z axis
    clippingPlaneZ: 0.48
    # indicates if the labeled and colored clouds have to be written to disk (writes it once)
    writeClouds: true


##### grasper node options #####
analyzer:
    # max distance between two points to be considered as in the same neighborhood
    epsilon: 0.01
    # number of points in a neighborhood for a point to be considered core point
    minPoints: 30
    # color palette used for the debug graph generation
    palette: Set3 # Options are: Spectral, Set1, Set2, Set3


##### grasper node options #####
grasper:
    # parameters regarding the use of a previously trained classifier for grasps
    classifier:
      use: false
      location: config/classifier_svm.yaml
    # arm used for grasping tasks
    arm: right # right or left
    # margin used for the collision object
    collisionMargin: 0.04
    # gap between object and effector at the begin of the grasping
    graspPadding: 0.15
    # mocks the grasp routine without actually moving the robot
    mockExecution: false


##### evaluator node options #####
evaluator:
    # positions to clip the cloud in planes X and Z (position and normal orientation)
    clippingZ: {p: 0.8, n: 1}
    clippingX: {p: 0.6, n: -1}
    # minimum number of positive poses o decide that a grasp was successful (1 to 4)
    successThreshold: 1
    # number of retries when moving the effector to the evaluation poses (-1 for no limit)
    maxRetries: 15
    # object position for evaluation of grasping attempt (relative to 'base_footprint')
    position: {x: 0.45, y: 0, z: 0.8}
    # point cloud input topic
    pointcloudTopic: /move_group/filtered_cloud 


########## descriptor params ##########

# radius used for the normal vectors estimation (-1 to use the 10 closest points)
normalEstimationRadius: -1

##### descriptor calculation params #####
descriptor:
    patchSize: 0.02 # mts
    bandNumber: 8
    bandWidth: 0.005 # mts
    bidirectional: false
    useProjection: false
    sequenceBin: 0.005 # mts
    sequenceStat: mean # mean or median

##### cloud smoothing params #####
cloudSmoothing:
    useSmoothing: true
    sigma: 4
    radius: 0.005
...