---
# flag to enable/disable debug
labelerDebug: false
analyzerDebug: false
grasperDebug: false


##### setup node options #####
setup:
    # true if torso/arms/base/head setup has to be performed
    liftTorso: false
    moveArms: true
    moveBase: false
    moveHead: true

    # setup positions 
    torsoPosition: 0.19
    displacementThreshold: 1.0
    headTarget: {x: 0.9, y: 0.0, z: 0.5}
    armsPosition:
      right: {x: 0.3, y: -0.5, z: 1.0}
      left: {x: 0.3, y: 0.5, z: 1.0}


##### labeler node options #####
labeler:
    # point cloud input topic
    pointcloudTopic: '/move_group/filtered_cloud' # '/head_mount_kinect/depth/points'
    # sampling voxel size
    voxelSize: 0.005
    # location of the BoW file
    bowLocation: 'src/grasping/config/bow50_c7_1E-4_opencv.dat'
    # clipping plane position in Z axis
    clippingPlaneZ: 0.62
    # indicates if the labeled and colored clouds have to be written to disk (writes it once)
    writeClouds: false


##### grasper node options #####
grasper:
    # arm used for grasping tasks
    arm: right # right or left
    # length allowed for the queue of GraspingPointArray messages
    queueMaxsize: 1
    # margin used for the collision object
    collisionMargin: 0.05


########## descriptor params ##########

# radius used for the normal vectors estimation
normalEstimationRadius: -1

##### descriptor calculation params #####
descriptor:
    patchSize: 0.02
    bandNumber: 8
    bandWidth: 0.005
    bidirectional: false
    useProjection: false
    sequenceBin: 0.005
    sequenceStat: mean # mean or median

##### cloud smoothing params #####
cloudSmoothing:
    useSmoothing: true
    sigma: 4
    radius: 0.005
...