---
models:
    {
      cinder_block: '/home/rodrigo/.gazebo/models/cinder_block/model-1_4.sdf',
      cordless_drill: '/home/rodrigo/.gazebo/models/cordless_drill/model-1_4.sdf',
      hammer: '/home/rodrigo/.gazebo/models/hammer/model-1_4.sdf',
      monkey_wrench: '/home/rodrigo/.gazebo/models/monkey_wrench/model-1_4.sdf',
      low_table: '/home/rodrigo/.gazebo/models/low_table/model-1_4.sdf',
      thin_beer: '/home/rodrigo/.gazebo/models/thin_beer/model-1_4.sdf',
      tube_9_5mm: '/home/rodrigo/.gazebo/models/tube_9_5mm/model-1_4.sdf',
      wood_cube_5cm: '/home/rodrigo/.gazebo/models/wood_cube_5cm/model-1_4.sdf',
    }
...